# Generated by Django 3.0.3 on 2020-03-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post2',
        ),
    ]
